api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    eager_loading:
        max_joins: 40
    collection:
        pagination:
            enabled: false
            items_per_page: 30
            client_enabled: true
            client_items_per_page: true
    mercure:
        enabled: true
        hub_url: '%env(MERCURE_URL)%'
