<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20210916072007 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        // $this->addSql('CREATE TABLE about_us (id INT AUTO_INCREMENT NOT NULL, service_picture_id INT DEFAULT NULL, product_picture_id INT DEFAULT NULL, support_picture_id INT DEFAULT NULL, header_picture_id INT DEFAULT NULL, summary LONGTEXT DEFAULT NULL, vision LONGTEXT DEFAULT NULL, mission LONGTEXT DEFAULT NULL, goal LONGTEXT DEFAULT NULL, vision_title VARCHAR(120) DEFAULT NULL, mission_title VARCHAR(120) DEFAULT NULL, goal_title VARCHAR(120) DEFAULT NULL, service_title VARCHAR(120) DEFAULT NULL, product_title VARCHAR(120) DEFAULT NULL, support_title VARCHAR(120) DEFAULT NULL, vision_color VARCHAR(20) DEFAULT NULL, mission_color VARCHAR(20) DEFAULT NULL, goal_color VARCHAR(20) DEFAULT NULL, service_color VARCHAR(20) DEFAULT NULL, product_color VARCHAR(20) DEFAULT NULL, support_color VARCHAR(20) DEFAULT NULL, header_title VARCHAR(255) DEFAULT NULL, header_subtitle VARCHAR(255) DEFAULT NULL, header_title_color VARCHAR(20) DEFAULT NULL, header_subtitle_color VARCHAR(20) DEFAULT NULL, UNIQUE INDEX UNIQ_B52303C37814840B (service_picture_id), UNIQUE INDEX UNIQ_B52303C37D22E294 (product_picture_id), UNIQUE INDEX UNIQ_B52303C3CCF1799D (support_picture_id), UNIQUE INDEX UNIQ_B52303C34C92AD88 (header_picture_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE agent (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, role VARCHAR(120) DEFAULT NULL, UNIQUE INDEX UNIQ_268B9C9D3DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE article (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, summary LONGTEXT DEFAULT NULL, content LONGTEXT DEFAULT NULL, published_at DATETIME DEFAULT NULL, visible TINYINT(1) DEFAULT NULL, UNIQUE INDEX UNIQ_23A0E663DA5256D (image_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE banner (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, image_id INT DEFAULT NULL, homepage_id INT DEFAULT NULL, title VARCHAR(120) DEFAULT NULL, subtitle VARCHAR(255) DEFAULT NULL, link VARCHAR(255) DEFAULT NULL, is_main TINYINT(1) DEFAULT NULL, banner_number INT DEFAULT NULL, text_color VARCHAR(20) DEFAULT NULL, title_color VARCHAR(20) DEFAULT NULL, text_shadow TINYINT(1) DEFAULT NULL, INDEX IDX_6F9DB8E74584665A (product_id), UNIQUE INDEX UNIQ_6F9DB8E73DA5256D (image_id), INDEX IDX_6F9DB8E7571EDDA (homepage_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE catalog (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, code VARCHAR(60) DEFAULT NULL, needs_parcel TINYINT(1) DEFAULT NULL, center LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', min_lat DOUBLE PRECISION DEFAULT NULL, max_lat DOUBLE PRECISION DEFAULT NULL, min_lng DOUBLE PRECISION DEFAULT NULL, max_lng DOUBLE PRECISION DEFAULT NULL, is_default TINYINT(1) DEFAULT NULL, zoom INT DEFAULT NULL, is_active TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE catalog_price (id INT AUTO_INCREMENT NOT NULL, catalog_id INT DEFAULT NULL, container_id INT DEFAULT NULL, amount DOUBLE PRECISION DEFAULT NULL, INDEX IDX_73DB4360CC3C66FC (catalog_id), INDEX IDX_73DB4360BC21F742 (container_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE catalog_tax (id INT AUTO_INCREMENT NOT NULL, catalog_id INT DEFAULT NULL, tax_id INT DEFAULT NULL, percent DOUBLE PRECISION DEFAULT NULL, INDEX IDX_519250B4CC3C66FC (catalog_id), INDEX IDX_519250B4B2A824D8 (tax_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE category_group (category_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_85F30B8C12469DE2 (category_id), INDEX IDX_85F30B8CFE54D947 (group_id), PRIMARY KEY(category_id, group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE category_catalog (category_id INT NOT NULL, catalog_id INT NOT NULL, INDEX IDX_DCF4723912469DE2 (category_id), INDEX IDX_DCF47239CC3C66FC (catalog_id), PRIMARY KEY(category_id, catalog_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE city (id INT AUTO_INCREMENT NOT NULL, zone_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, zip_code VARCHAR(20) DEFAULT NULL, INDEX IDX_2D5B02349F2C3FAB (zone_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE city_condition (city_id INT NOT NULL, condition_id INT NOT NULL, INDEX IDX_198294568BAC62AF (city_id), INDEX IDX_19829456887793B6 (condition_id), PRIMARY KEY(city_id, condition_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE component (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, variation_id INT DEFAULT NULL, size_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, quantity DOUBLE PRECISION DEFAULT NULL, INDEX IDX_49FEA1574584665A (product_id), INDEX IDX_49FEA1575182BFD8 (variation_id), INDEX IDX_49FEA157498DA827 (size_id), INDEX IDX_49FEA1577E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE `condition` (id INT AUTO_INCREMENT NOT NULL, tax_id INT DEFAULT NULL, days LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', price DOUBLE PRECISION DEFAULT NULL, min_for_free DOUBLE PRECISION DEFAULT NULL, is_relaypoint TINYINT(1) DEFAULT NULL, INDEX IDX_BDD68843B2A824D8 (tax_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE condition_group (condition_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_211BA0CE887793B6 (condition_id), INDEX IDX_211BA0CEFE54D947 (group_id), PRIMARY KEY(condition_id, group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE container (id INT AUTO_INCREMENT NOT NULL, tax_id INT DEFAULT NULL, stock_id INT DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, max DOUBLE PRECISION DEFAULT NULL, tare DOUBLE PRECISION DEFAULT NULL, height DOUBLE PRECISION DEFAULT NULL, width DOUBLE PRECISION DEFAULT NULL, length DOUBLE PRECISION DEFAULT NULL, available TINYINT(1) DEFAULT NULL, accounting_id INT DEFAULT NULL, INDEX IDX_C7A2EC1BB2A824D8 (tax_id), UNIQUE INDEX UNIQ_C7A2EC1BDCD6110 (stock_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE countdown (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, homepage_id INT DEFAULT NULL, product_id INT DEFAULT NULL, date DATETIME DEFAULT NULL, text_color VARCHAR(20) DEFAULT NULL, text_shadow TINYINT(1) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, button_text VARCHAR(20) DEFAULT NULL, UNIQUE INDEX UNIQ_376B83563DA5256D (image_id), INDEX IDX_376B8356571EDDA (homepage_id), INDEX IDX_376B83564584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE cron_job (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(191) NOT NULL, command VARCHAR(1024) NOT NULL, schedule VARCHAR(191) NOT NULL, description VARCHAR(191) NOT NULL, enabled TINYINT(1) NOT NULL, UNIQUE INDEX un_name (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE cron_report (id INT AUTO_INCREMENT NOT NULL, job_id INT DEFAULT NULL, run_at DATETIME NOT NULL, run_time DOUBLE PRECISION NOT NULL, exit_code INT NOT NULL, output LONGTEXT NOT NULL, INDEX IDX_B6C6A7F5BE04EA9 (job_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE day_off (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) DEFAULT NULL, date DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE day_off_group (day_off_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_94BBF0F27E81C1E1 (day_off_id), INDEX IDX_94BBF0F2FE54D947 (group_id), PRIMARY KEY(day_off_id, group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE deliverer (id INT AUTO_INCREMENT NOT NULL, tax_id INT DEFAULT NULL, catalog_id INT DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, is_intern TINYINT(1) DEFAULT NULL, cost DOUBLE PRECISION DEFAULT NULL, is_percent TINYINT(1) DEFAULT NULL, total_to_pay DOUBLE PRECISION DEFAULT NULL, total_to_pay_ttc DOUBLE PRECISION DEFAULT NULL, turnover DOUBLE PRECISION DEFAULT NULL, turnover_ttc DOUBLE PRECISION DEFAULT NULL, owner_rate DOUBLE PRECISION DEFAULT NULL, INDEX IDX_97FE3348B2A824D8 (tax_id), INDEX IDX_97FE3348CC3C66FC (catalog_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE deliverer_user (deliverer_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_DBF1A092B6A6A3F4 (deliverer_id), INDEX IDX_DBF1A092A76ED395 (user_id), PRIMARY KEY(deliverer_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE good (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, provision_id INT DEFAULT NULL, variation_id INT DEFAULT NULL, size_id INT DEFAULT NULL, quantity DOUBLE PRECISION DEFAULT NULL, unit VARCHAR(12) DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, received DOUBLE PRECISION DEFAULT NULL, INDEX IDX_6C844E924584665A (product_id), INDEX IDX_6C844E923EC01A31 (provision_id), INDEX IDX_6C844E925182BFD8 (variation_id), INDEX IDX_6C844E92498DA827 (size_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE `group` (id INT AUTO_INCREMENT NOT NULL, price_group_id INT DEFAULT NULL, label VARCHAR(30) DEFAULT NULL, value VARCHAR(35) DEFAULT NULL, is_fixed TINYINT(1) DEFAULT NULL, subject_to_taxes TINYINT(1) DEFAULT NULL, day_interval INT DEFAULT NULL, hour_limit TIME DEFAULT NULL, online_payment TINYINT(1) DEFAULT NULL, has_admin_access TINYINT(1) DEFAULT NULL, has_shop_access TINYINT(1) DEFAULT NULL, sold_out_notification TINYINT(1) DEFAULT NULL, INDEX IDX_6DC044C59CE2E250 (price_group_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE hero (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, homepage_id INT DEFAULT NULL, product_id INT DEFAULT NULL, title VARCHAR(120) DEFAULT NULL, subtitle VARCHAR(255) DEFAULT NULL, text_color VARCHAR(20) DEFAULT NULL, title_color VARCHAR(20) DEFAULT NULL, text_shadow TINYINT(1) DEFAULT NULL, UNIQUE INDEX UNIQ_51CE6E863DA5256D (image_id), INDEX IDX_51CE6E86571EDDA (homepage_id), INDEX IDX_51CE6E864584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE homepage (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(150) DEFAULT NULL, selected TINYINT(1) DEFAULT NULL, banners_number INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE item (id INT AUTO_INCREMENT NOT NULL, product_id INT DEFAULT NULL, order_entity_id INT DEFAULT NULL, variation_id INT DEFAULT NULL, size_id INT DEFAULT NULL, ordered_qty DOUBLE PRECISION DEFAULT NULL, prepared_qty DOUBLE PRECISION DEFAULT NULL, delivered_qty DOUBLE PRECISION DEFAULT NULL, price DOUBLE PRECISION DEFAULT NULL, tax_rate DOUBLE PRECISION DEFAULT NULL, is_adjourned TINYINT(1) DEFAULT NULL, is_prepared TINYINT(1) DEFAULT NULL, unit VARCHAR(10) DEFAULT NULL, INDEX IDX_1F1B251E4584665A (product_id), INDEX IDX_1F1B251E3DA206A5 (order_entity_id), INDEX IDX_1F1B251E5182BFD8 (variation_id), INDEX IDX_1F1B251E498DA827 (size_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE message (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, subject VARCHAR(255) DEFAULT NULL, message LONGTEXT DEFAULT NULL, sent_at DATETIME DEFAULT NULL, is_read TINYINT(1) DEFAULT NULL, response LONGTEXT DEFAULT NULL, replied TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE meta (id INT AUTO_INCREMENT NOT NULL, address VARCHAR(255) DEFAULT NULL, address2 VARCHAR(255) DEFAULT NULL, zipcode VARCHAR(10) DEFAULT NULL, city VARCHAR(100) DEFAULT NULL, position LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', phone VARCHAR(15) DEFAULT NULL, is_relaypoint TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE order_entity (id INT AUTO_INCREMENT NOT NULL, metas_id INT DEFAULT NULL, user_id INT DEFAULT NULL, catalog_id INT DEFAULT NULL, promotion_id INT DEFAULT NULL, applied_condition_id INT DEFAULT NULL, touring_id INT DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, email VARCHAR(120) DEFAULT NULL, delivery_date DATETIME DEFAULT NULL, status VARCHAR(50) DEFAULT NULL, is_remains TINYINT(1) DEFAULT NULL, total_ht DOUBLE PRECISION DEFAULT NULL, total_ttc DOUBLE PRECISION DEFAULT NULL, message LONGTEXT DEFAULT NULL, payment_id VARCHAR(255) DEFAULT NULL, uuid CHAR(36) DEFAULT NULL COMMENT \'(DC2Type:guid)\', delivery_priority INT DEFAULT NULL, regulated TINYINT(1) DEFAULT NULL, track_ids LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', reservation_number VARCHAR(50) DEFAULT NULL, invoiced TINYINT(1) DEFAULT NULL, invoice_id INT DEFAULT NULL, INDEX IDX_CDA754BD23290B3B (metas_id), INDEX IDX_CDA754BDA76ED395 (user_id), INDEX IDX_CDA754BDCC3C66FC (catalog_id), INDEX IDX_CDA754BD139DF194 (promotion_id), INDEX IDX_CDA754BDCF479569 (applied_condition_id), INDEX IDX_CDA754BD36BD1931 (touring_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE package (id INT AUTO_INCREMENT NOT NULL, container_id INT DEFAULT NULL, order_entity_id INT DEFAULT NULL, quantity INT DEFAULT NULL, INDEX IDX_DE686795BC21F742 (container_id), INDEX IDX_DE6867953DA206A5 (order_entity_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE picture (id INT AUTO_INCREMENT NOT NULL, file_path VARCHAR(255) DEFAULT NULL, img_path VARCHAR(255) DEFAULT NULL, link_instance VARCHAR(120) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE platform (id INT AUTO_INCREMENT NOT NULL, metas_id INT DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, UNIQUE INDEX UNIQ_3952D0CB23290B3B (metas_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE platform_user (platform_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_99BB165FFE6496F (platform_id), INDEX IDX_99BB165A76ED395 (user_id), PRIMARY KEY(platform_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE price (id INT AUTO_INCREMENT NOT NULL, price_group_id INT DEFAULT NULL, product_id INT DEFAULT NULL, amount DOUBLE PRECISION DEFAULT NULL, INDEX IDX_CAC822D99CE2E250 (price_group_id), INDEX IDX_CAC822D94584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE price_group (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(60) DEFAULT NULL, rate DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE product (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, tax_id INT DEFAULT NULL, stock_id INT DEFAULT NULL, seller_id INT DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, sku VARCHAR(20) DEFAULT NULL, discount DOUBLE PRECISION DEFAULT NULL, offer_end DATETIME DEFAULT NULL, full_description LONGTEXT DEFAULT NULL, sale_count INT DEFAULT NULL, new TINYINT(1) DEFAULT NULL, available TINYINT(1) DEFAULT NULL, stock_managed TINYINT(1) DEFAULT NULL, require_legal_age TINYINT(1) DEFAULT NULL, unit VARCHAR(12) DEFAULT NULL, weight DOUBLE PRECISION DEFAULT NULL, product_group VARCHAR(60) DEFAULT NULL, is_mixed TINYINT(1) DEFAULT NULL, updated_at DATETIME DEFAULT NULL, is_fabricated TINYINT(1) DEFAULT NULL, is_sold TINYINT(1) DEFAULT NULL, last_cost DOUBLE PRECISION DEFAULT NULL, require_declaration TINYINT(1) DEFAULT NULL, content_weight DOUBLE PRECISION DEFAULT NULL, accounting_id INT DEFAULT NULL, UNIQUE INDEX UNIQ_D34A04AD3DA5256D (image_id), INDEX IDX_D34A04ADB2A824D8 (tax_id), UNIQUE INDEX UNIQ_D34A04ADDCD6110 (stock_id), INDEX IDX_D34A04AD8DE820D9 (seller_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE product_category (product_id INT NOT NULL, category_id INT NOT NULL, INDEX IDX_CDFC73564584665A (product_id), INDEX IDX_CDFC735612469DE2 (category_id), PRIMARY KEY(product_id, category_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE product_group (product_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_CC9C3F994584665A (product_id), INDEX IDX_CC9C3F99FE54D947 (group_id), PRIMARY KEY(product_id, group_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE product_catalog (product_id INT NOT NULL, catalog_id INT NOT NULL, INDEX IDX_CAF529F74584665A (product_id), INDEX IDX_CAF529F7CC3C66FC (catalog_id), PRIMARY KEY(product_id, catalog_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE promotion (id INT AUTO_INCREMENT NOT NULL, code VARCHAR(15) DEFAULT NULL, percentage TINYINT(1) DEFAULT NULL, discount DOUBLE PRECISION DEFAULT NULL, max_usage INT DEFAULT NULL, used INT DEFAULT NULL, ends_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE provision (id INT AUTO_INCREMENT NOT NULL, supplier_id INT DEFAULT NULL, seller_id INT DEFAULT NULL, provision_date DATETIME DEFAULT NULL, status VARCHAR(120) DEFAULT NULL, integrated TINYINT(1) DEFAULT NULL, INDEX IDX_BA9B42902ADD6D8C (supplier_id), INDEX IDX_BA9B42908DE820D9 (seller_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE relaypoint (id INT AUTO_INCREMENT NOT NULL, metas_id INT DEFAULT NULL, promotion_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, available TINYINT(1) DEFAULT NULL, private TINYINT(1) DEFAULT NULL, access_code VARCHAR(30) DEFAULT NULL, informations LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_F0ED53AD23290B3B (metas_id), UNIQUE INDEX UNIQ_F0ED53AD139DF194 (promotion_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE relaypoint_condition (relaypoint_id INT NOT NULL, condition_id INT NOT NULL, INDEX IDX_9B98DFE5F8CC9BA1 (relaypoint_id), INDEX IDX_9B98DFE5887793B6 (condition_id), PRIMARY KEY(relaypoint_id, condition_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE relaypoint_user (relaypoint_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_343FFF77F8CC9BA1 (relaypoint_id), INDEX IDX_343FFF77A76ED395 (user_id), PRIMARY KEY(relaypoint_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE reset_password (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(255) DEFAULT NULL, token VARCHAR(60) DEFAULT NULL, is_used TINYINT(1) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE restriction (id INT AUTO_INCREMENT NOT NULL, catalog_id INT DEFAULT NULL, category_id INT DEFAULT NULL, quantity DOUBLE PRECISION DEFAULT NULL, unit VARCHAR(15) DEFAULT NULL, INDEX IDX_7A999BCECC3C66FC (catalog_id), INDEX IDX_7A999BCE12469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE seller (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) DEFAULT NULL, delay INT DEFAULT NULL, owner_rate DOUBLE PRECISION DEFAULT NULL, turnover DOUBLE PRECISION DEFAULT NULL, total_to_pay DOUBLE PRECISION DEFAULT NULL, needs_recovery TINYINT(1) DEFAULT NULL, delay_in_days TINYINT(1) DEFAULT NULL, recovery_delay INT DEFAULT NULL, turnover_ttc DOUBLE PRECISION DEFAULT NULL, total_to_pay_ttc DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE seller_user (seller_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_8F6A13A98DE820D9 (seller_id), INDEX IDX_8F6A13A9A76ED395 (user_id), PRIMARY KEY(seller_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE size (id INT AUTO_INCREMENT NOT NULL, stock_id INT DEFAULT NULL, variation_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_F7C0246ADCD6110 (stock_id), INDEX IDX_F7C0246A5182BFD8 (variation_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE stock (id INT AUTO_INCREMENT NOT NULL, quantity DOUBLE PRECISION DEFAULT NULL, security DOUBLE PRECISION DEFAULT NULL, alert DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE supervisor (id INT AUTO_INCREMENT NOT NULL, supervisor_id INT DEFAULT NULL, role VARCHAR(120) DEFAULT NULL, UNIQUE INDEX UNIQ_4D9192F819E9AC5F (supervisor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE supervisor_user (supervisor_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_6BD776E19E9AC5F (supervisor_id), INDEX IDX_6BD776EA76ED395 (user_id), PRIMARY KEY(supervisor_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE supplier (id INT AUTO_INCREMENT NOT NULL, seller_id INT DEFAULT NULL, name VARCHAR(120) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, phone VARCHAR(15) DEFAULT NULL, accounting_id INT DEFAULT NULL, accounting_company_id INT DEFAULT NULL, INDEX IDX_9B2A6C7E8DE820D9 (seller_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE tax (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(120) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE touring (id INT AUTO_INCREMENT NOT NULL, deliverer_id INT DEFAULT NULL, start DATETIME DEFAULT NULL, end DATETIME DEFAULT NULL, is_open TINYINT(1) DEFAULT NULL, position LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:array)\', regulated TINYINT(1) DEFAULT NULL, INDEX IDX_E343D31CB6A6A3F4 (deliverer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, metas_id INT DEFAULT NULL, email VARCHAR(180) NOT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', password VARCHAR(255) NOT NULL, name VARCHAR(100) DEFAULT NULL, order_count INT DEFAULT NULL, last_order DATETIME DEFAULT NULL, accounting_id INT DEFAULT NULL, billing_details TINYINT(1) DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), UNIQUE INDEX UNIQ_8D93D64923290B3B (metas_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE variation (id INT AUTO_INCREMENT NOT NULL, image_id INT DEFAULT NULL, product_id INT DEFAULT NULL, color VARCHAR(60) DEFAULT NULL, UNIQUE INDEX UNIQ_629B33EA3DA5256D (image_id), INDEX IDX_629B33EA4584665A (product_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('CREATE TABLE zone (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        // $this->addSql('ALTER TABLE about_us ADD CONSTRAINT FK_B52303C37814840B FOREIGN KEY (service_picture_id) REFERENCES picture (id)');
        // $this->addSql('ALTER TABLE about_us ADD CONSTRAINT FK_B52303C37D22E294 FOREIGN KEY (product_picture_id) REFERENCES picture (id)');
        // $this->addSql('ALTER TABLE about_us ADD CONSTRAINT FK_B52303C3CCF1799D FOREIGN KEY (support_picture_id) REFERENCES picture (id)');
        // $this->addSql('ALTER TABLE about_us ADD CONSTRAINT FK_B52303C34C92AD88 FOREIGN KEY (header_picture_id) REFERENCES picture (id)');
        // $this->addSql('ALTER TABLE agent ADD CONSTRAINT FK_268B9C9D3DA5256D FOREIGN KEY (image_id) REFERENCES picture (id)');
        // $this->addSql('ALTER TABLE article ADD CONSTRAINT FK_23A0E663DA5256D FOREIGN KEY (image_id) REFERENCES picture (id)');
        // $this->addSql('ALTER TABLE banner ADD CONSTRAINT FK_6F9DB8E74584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        // $this->addSql('ALTER TABLE banner ADD CONSTRAINT FK_6F9DB8E73DA5256D FOREIGN KEY (image_id) REFERENCES picture (id)');
        // $this->addSql('ALTER TABLE banner ADD CONSTRAINT FK_6F9DB8E7571EDDA FOREIGN KEY (homepage_id) REFERENCES homepage (id)');
        // $this->addSql('ALTER TABLE catalog_price ADD CONSTRAINT FK_73DB4360CC3C66FC FOREIGN KEY (catalog_id) REFERENCES catalog (id)');
        // $this->addSql('ALTER TABLE catalog_price ADD CONSTRAINT FK_73DB4360BC21F742 FOREIGN KEY (container_id) REFERENCES container (id)');
        // $this->addSql('ALTER TABLE catalog_tax ADD CONSTRAINT FK_519250B4CC3C66FC FOREIGN KEY (catalog_id) REFERENCES catalog (id)');
        // $this->addSql('ALTER TABLE catalog_tax ADD CONSTRAINT FK_519250B4B2A824D8 FOREIGN KEY (tax_id) REFERENCES tax (id)');
        // $this->addSql('ALTER TABLE category_group ADD CONSTRAINT FK_85F30B8C12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE category_group ADD CONSTRAINT FK_85F30B8CFE54D947 FOREIGN KEY (group_id) REFERENCES `group` (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE category_catalog ADD CONSTRAINT FK_DCF4723912469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE category_catalog ADD CONSTRAINT FK_DCF47239CC3C66FC FOREIGN KEY (catalog_id) REFERENCES catalog (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B02349F2C3FAB FOREIGN KEY (zone_id) REFERENCES zone (id)');
        // $this->addSql('ALTER TABLE city_condition ADD CONSTRAINT FK_198294568BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE city_condition ADD CONSTRAINT FK_19829456887793B6 FOREIGN KEY (condition_id) REFERENCES `condition` (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE component ADD CONSTRAINT FK_49FEA1574584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        // $this->addSql('ALTER TABLE component ADD CONSTRAINT FK_49FEA1575182BFD8 FOREIGN KEY (variation_id) REFERENCES variation (id)');
        // $this->addSql('ALTER TABLE component ADD CONSTRAINT FK_49FEA157498DA827 FOREIGN KEY (size_id) REFERENCES size (id)');
        // $this->addSql('ALTER TABLE component ADD CONSTRAINT FK_49FEA1577E3C61F9 FOREIGN KEY (owner_id) REFERENCES product (id)');
        // $this->addSql('ALTER TABLE `condition` ADD CONSTRAINT FK_BDD68843B2A824D8 FOREIGN KEY (tax_id) REFERENCES tax (id)');
        // $this->addSql('ALTER TABLE condition_group ADD CONSTRAINT FK_211BA0CE887793B6 FOREIGN KEY (condition_id) REFERENCES `condition` (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE condition_group ADD CONSTRAINT FK_211BA0CEFE54D947 FOREIGN KEY (group_id) REFERENCES `group` (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE container ADD CONSTRAINT FK_C7A2EC1BB2A824D8 FOREIGN KEY (tax_id) REFERENCES tax (id)');
        // $this->addSql('ALTER TABLE container ADD CONSTRAINT FK_C7A2EC1BDCD6110 FOREIGN KEY (stock_id) REFERENCES stock (id)');
        // $this->addSql('ALTER TABLE countdown ADD CONSTRAINT FK_376B83563DA5256D FOREIGN KEY (image_id) REFERENCES picture (id)');
        // $this->addSql('ALTER TABLE countdown ADD CONSTRAINT FK_376B8356571EDDA FOREIGN KEY (homepage_id) REFERENCES homepage (id)');
        // $this->addSql('ALTER TABLE countdown ADD CONSTRAINT FK_376B83564584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        // $this->addSql('ALTER TABLE cron_report ADD CONSTRAINT FK_B6C6A7F5BE04EA9 FOREIGN KEY (job_id) REFERENCES cron_job (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE day_off_group ADD CONSTRAINT FK_94BBF0F27E81C1E1 FOREIGN KEY (day_off_id) REFERENCES day_off (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE day_off_group ADD CONSTRAINT FK_94BBF0F2FE54D947 FOREIGN KEY (group_id) REFERENCES `group` (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE deliverer ADD CONSTRAINT FK_97FE3348B2A824D8 FOREIGN KEY (tax_id) REFERENCES tax (id)');
        // $this->addSql('ALTER TABLE deliverer ADD CONSTRAINT FK_97FE3348CC3C66FC FOREIGN KEY (catalog_id) REFERENCES catalog (id)');
        // $this->addSql('ALTER TABLE deliverer_user ADD CONSTRAINT FK_DBF1A092B6A6A3F4 FOREIGN KEY (deliverer_id) REFERENCES deliverer (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE deliverer_user ADD CONSTRAINT FK_DBF1A092A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE good ADD CONSTRAINT FK_6C844E924584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        // $this->addSql('ALTER TABLE good ADD CONSTRAINT FK_6C844E923EC01A31 FOREIGN KEY (provision_id) REFERENCES provision (id)');
        // $this->addSql('ALTER TABLE good ADD CONSTRAINT FK_6C844E925182BFD8 FOREIGN KEY (variation_id) REFERENCES variation (id)');
        // $this->addSql('ALTER TABLE good ADD CONSTRAINT FK_6C844E92498DA827 FOREIGN KEY (size_id) REFERENCES size (id)');
        // $this->addSql('ALTER TABLE `group` ADD CONSTRAINT FK_6DC044C59CE2E250 FOREIGN KEY (price_group_id) REFERENCES price_group (id)');
        // $this->addSql('ALTER TABLE hero ADD CONSTRAINT FK_51CE6E863DA5256D FOREIGN KEY (image_id) REFERENCES picture (id)');
        // $this->addSql('ALTER TABLE hero ADD CONSTRAINT FK_51CE6E86571EDDA FOREIGN KEY (homepage_id) REFERENCES homepage (id)');
        // $this->addSql('ALTER TABLE hero ADD CONSTRAINT FK_51CE6E864584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        // $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251E4584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        // $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251E3DA206A5 FOREIGN KEY (order_entity_id) REFERENCES order_entity (id)');
        // $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251E5182BFD8 FOREIGN KEY (variation_id) REFERENCES variation (id)');
        // $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251E498DA827 FOREIGN KEY (size_id) REFERENCES size (id)');
        // $this->addSql('ALTER TABLE order_entity ADD CONSTRAINT FK_CDA754BD23290B3B FOREIGN KEY (metas_id) REFERENCES meta (id)');
        // $this->addSql('ALTER TABLE order_entity ADD CONSTRAINT FK_CDA754BDA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        // $this->addSql('ALTER TABLE order_entity ADD CONSTRAINT FK_CDA754BDCC3C66FC FOREIGN KEY (catalog_id) REFERENCES catalog (id)');
        // $this->addSql('ALTER TABLE order_entity ADD CONSTRAINT FK_CDA754BD139DF194 FOREIGN KEY (promotion_id) REFERENCES promotion (id)');
        // $this->addSql('ALTER TABLE order_entity ADD CONSTRAINT FK_CDA754BDCF479569 FOREIGN KEY (applied_condition_id) REFERENCES `condition` (id)');
        // $this->addSql('ALTER TABLE order_entity ADD CONSTRAINT FK_CDA754BD36BD1931 FOREIGN KEY (touring_id) REFERENCES touring (id)');
        // $this->addSql('ALTER TABLE package ADD CONSTRAINT FK_DE686795BC21F742 FOREIGN KEY (container_id) REFERENCES container (id)');
        // $this->addSql('ALTER TABLE package ADD CONSTRAINT FK_DE6867953DA206A5 FOREIGN KEY (order_entity_id) REFERENCES order_entity (id)');
        // $this->addSql('ALTER TABLE platform ADD CONSTRAINT FK_3952D0CB23290B3B FOREIGN KEY (metas_id) REFERENCES meta (id)');
        // $this->addSql('ALTER TABLE platform_user ADD CONSTRAINT FK_99BB165FFE6496F FOREIGN KEY (platform_id) REFERENCES platform (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE platform_user ADD CONSTRAINT FK_99BB165A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE price ADD CONSTRAINT FK_CAC822D99CE2E250 FOREIGN KEY (price_group_id) REFERENCES price_group (id)');
        // $this->addSql('ALTER TABLE price ADD CONSTRAINT FK_CAC822D94584665A FOREIGN KEY (product_id) REFERENCES product (id)');
        // $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD3DA5256D FOREIGN KEY (image_id) REFERENCES picture (id)');
        // $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADB2A824D8 FOREIGN KEY (tax_id) REFERENCES tax (id)');
        // $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04ADDCD6110 FOREIGN KEY (stock_id) REFERENCES stock (id)');
        // $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD8DE820D9 FOREIGN KEY (seller_id) REFERENCES seller (id)');
        // $this->addSql('ALTER TABLE product_category ADD CONSTRAINT FK_CDFC73564584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE product_category ADD CONSTRAINT FK_CDFC735612469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE product_group ADD CONSTRAINT FK_CC9C3F994584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE product_group ADD CONSTRAINT FK_CC9C3F99FE54D947 FOREIGN KEY (group_id) REFERENCES `group` (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE product_catalog ADD CONSTRAINT FK_CAF529F74584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE product_catalog ADD CONSTRAINT FK_CAF529F7CC3C66FC FOREIGN KEY (catalog_id) REFERENCES catalog (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE provision ADD CONSTRAINT FK_BA9B42902ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id)');
        // $this->addSql('ALTER TABLE provision ADD CONSTRAINT FK_BA9B42908DE820D9 FOREIGN KEY (seller_id) REFERENCES seller (id)');
        // $this->addSql('ALTER TABLE relaypoint ADD CONSTRAINT FK_F0ED53AD23290B3B FOREIGN KEY (metas_id) REFERENCES meta (id)');
        // $this->addSql('ALTER TABLE relaypoint ADD CONSTRAINT FK_F0ED53AD139DF194 FOREIGN KEY (promotion_id) REFERENCES promotion (id)');
        // $this->addSql('ALTER TABLE relaypoint_condition ADD CONSTRAINT FK_9B98DFE5F8CC9BA1 FOREIGN KEY (relaypoint_id) REFERENCES relaypoint (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE relaypoint_condition ADD CONSTRAINT FK_9B98DFE5887793B6 FOREIGN KEY (condition_id) REFERENCES `condition` (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE relaypoint_user ADD CONSTRAINT FK_343FFF77F8CC9BA1 FOREIGN KEY (relaypoint_id) REFERENCES relaypoint (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE relaypoint_user ADD CONSTRAINT FK_343FFF77A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE restriction ADD CONSTRAINT FK_7A999BCECC3C66FC FOREIGN KEY (catalog_id) REFERENCES catalog (id)');
        // $this->addSql('ALTER TABLE restriction ADD CONSTRAINT FK_7A999BCE12469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        // $this->addSql('ALTER TABLE seller_user ADD CONSTRAINT FK_8F6A13A98DE820D9 FOREIGN KEY (seller_id) REFERENCES seller (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE seller_user ADD CONSTRAINT FK_8F6A13A9A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE size ADD CONSTRAINT FK_F7C0246ADCD6110 FOREIGN KEY (stock_id) REFERENCES stock (id)');
        // $this->addSql('ALTER TABLE size ADD CONSTRAINT FK_F7C0246A5182BFD8 FOREIGN KEY (variation_id) REFERENCES variation (id)');
        // $this->addSql('ALTER TABLE supervisor ADD CONSTRAINT FK_4D9192F819E9AC5F FOREIGN KEY (supervisor_id) REFERENCES user (id)');
        // $this->addSql('ALTER TABLE supervisor_user ADD CONSTRAINT FK_6BD776E19E9AC5F FOREIGN KEY (supervisor_id) REFERENCES supervisor (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE supervisor_user ADD CONSTRAINT FK_6BD776EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        // $this->addSql('ALTER TABLE supplier ADD CONSTRAINT FK_9B2A6C7E8DE820D9 FOREIGN KEY (seller_id) REFERENCES seller (id)');
        // $this->addSql('ALTER TABLE touring ADD CONSTRAINT FK_E343D31CB6A6A3F4 FOREIGN KEY (deliverer_id) REFERENCES deliverer (id)');
        // $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D64923290B3B FOREIGN KEY (metas_id) REFERENCES meta (id)');
        // $this->addSql('ALTER TABLE variation ADD CONSTRAINT FK_629B33EA3DA5256D FOREIGN KEY (image_id) REFERENCES picture (id)');
        // $this->addSql('ALTER TABLE variation ADD CONSTRAINT FK_629B33EA4584665A FOREIGN KEY (product_id) REFERENCES product (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        // $this->addSql('ALTER TABLE catalog_price DROP FOREIGN KEY FK_73DB4360CC3C66FC');
        // $this->addSql('ALTER TABLE catalog_tax DROP FOREIGN KEY FK_519250B4CC3C66FC');
        // $this->addSql('ALTER TABLE category_catalog DROP FOREIGN KEY FK_DCF47239CC3C66FC');
        // $this->addSql('ALTER TABLE deliverer DROP FOREIGN KEY FK_97FE3348CC3C66FC');
        // $this->addSql('ALTER TABLE order_entity DROP FOREIGN KEY FK_CDA754BDCC3C66FC');
        // $this->addSql('ALTER TABLE product_catalog DROP FOREIGN KEY FK_CAF529F7CC3C66FC');
        // $this->addSql('ALTER TABLE restriction DROP FOREIGN KEY FK_7A999BCECC3C66FC');
        // $this->addSql('ALTER TABLE category_group DROP FOREIGN KEY FK_85F30B8C12469DE2');
        // $this->addSql('ALTER TABLE category_catalog DROP FOREIGN KEY FK_DCF4723912469DE2');
        // $this->addSql('ALTER TABLE product_category DROP FOREIGN KEY FK_CDFC735612469DE2');
        // $this->addSql('ALTER TABLE restriction DROP FOREIGN KEY FK_7A999BCE12469DE2');
        // $this->addSql('ALTER TABLE city_condition DROP FOREIGN KEY FK_198294568BAC62AF');
        // $this->addSql('ALTER TABLE city_condition DROP FOREIGN KEY FK_19829456887793B6');
        // $this->addSql('ALTER TABLE condition_group DROP FOREIGN KEY FK_211BA0CE887793B6');
        // $this->addSql('ALTER TABLE order_entity DROP FOREIGN KEY FK_CDA754BDCF479569');
        // $this->addSql('ALTER TABLE relaypoint_condition DROP FOREIGN KEY FK_9B98DFE5887793B6');
        // $this->addSql('ALTER TABLE catalog_price DROP FOREIGN KEY FK_73DB4360BC21F742');
        // $this->addSql('ALTER TABLE package DROP FOREIGN KEY FK_DE686795BC21F742');
        // $this->addSql('ALTER TABLE cron_report DROP FOREIGN KEY FK_B6C6A7F5BE04EA9');
        // $this->addSql('ALTER TABLE day_off_group DROP FOREIGN KEY FK_94BBF0F27E81C1E1');
        // $this->addSql('ALTER TABLE deliverer_user DROP FOREIGN KEY FK_DBF1A092B6A6A3F4');
        // $this->addSql('ALTER TABLE touring DROP FOREIGN KEY FK_E343D31CB6A6A3F4');
        // $this->addSql('ALTER TABLE category_group DROP FOREIGN KEY FK_85F30B8CFE54D947');
        // $this->addSql('ALTER TABLE condition_group DROP FOREIGN KEY FK_211BA0CEFE54D947');
        // $this->addSql('ALTER TABLE day_off_group DROP FOREIGN KEY FK_94BBF0F2FE54D947');
        // $this->addSql('ALTER TABLE product_group DROP FOREIGN KEY FK_CC9C3F99FE54D947');
        // $this->addSql('ALTER TABLE banner DROP FOREIGN KEY FK_6F9DB8E7571EDDA');
        // $this->addSql('ALTER TABLE countdown DROP FOREIGN KEY FK_376B8356571EDDA');
        // $this->addSql('ALTER TABLE hero DROP FOREIGN KEY FK_51CE6E86571EDDA');
        // $this->addSql('ALTER TABLE order_entity DROP FOREIGN KEY FK_CDA754BD23290B3B');
        // $this->addSql('ALTER TABLE platform DROP FOREIGN KEY FK_3952D0CB23290B3B');
        // $this->addSql('ALTER TABLE relaypoint DROP FOREIGN KEY FK_F0ED53AD23290B3B');
        // $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D64923290B3B');
        // $this->addSql('ALTER TABLE item DROP FOREIGN KEY FK_1F1B251E3DA206A5');
        // $this->addSql('ALTER TABLE package DROP FOREIGN KEY FK_DE6867953DA206A5');
        // $this->addSql('ALTER TABLE about_us DROP FOREIGN KEY FK_B52303C37814840B');
        // $this->addSql('ALTER TABLE about_us DROP FOREIGN KEY FK_B52303C37D22E294');
        // $this->addSql('ALTER TABLE about_us DROP FOREIGN KEY FK_B52303C3CCF1799D');
        // $this->addSql('ALTER TABLE about_us DROP FOREIGN KEY FK_B52303C34C92AD88');
        // $this->addSql('ALTER TABLE agent DROP FOREIGN KEY FK_268B9C9D3DA5256D');
        // $this->addSql('ALTER TABLE article DROP FOREIGN KEY FK_23A0E663DA5256D');
        // $this->addSql('ALTER TABLE banner DROP FOREIGN KEY FK_6F9DB8E73DA5256D');
        // $this->addSql('ALTER TABLE countdown DROP FOREIGN KEY FK_376B83563DA5256D');
        // $this->addSql('ALTER TABLE hero DROP FOREIGN KEY FK_51CE6E863DA5256D');
        // $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD3DA5256D');
        // $this->addSql('ALTER TABLE variation DROP FOREIGN KEY FK_629B33EA3DA5256D');
        // $this->addSql('ALTER TABLE platform_user DROP FOREIGN KEY FK_99BB165FFE6496F');
        // $this->addSql('ALTER TABLE `group` DROP FOREIGN KEY FK_6DC044C59CE2E250');
        // $this->addSql('ALTER TABLE price DROP FOREIGN KEY FK_CAC822D99CE2E250');
        // $this->addSql('ALTER TABLE banner DROP FOREIGN KEY FK_6F9DB8E74584665A');
        // $this->addSql('ALTER TABLE component DROP FOREIGN KEY FK_49FEA1574584665A');
        // $this->addSql('ALTER TABLE component DROP FOREIGN KEY FK_49FEA1577E3C61F9');
        // $this->addSql('ALTER TABLE countdown DROP FOREIGN KEY FK_376B83564584665A');
        // $this->addSql('ALTER TABLE good DROP FOREIGN KEY FK_6C844E924584665A');
        // $this->addSql('ALTER TABLE hero DROP FOREIGN KEY FK_51CE6E864584665A');
        // $this->addSql('ALTER TABLE item DROP FOREIGN KEY FK_1F1B251E4584665A');
        // $this->addSql('ALTER TABLE price DROP FOREIGN KEY FK_CAC822D94584665A');
        // $this->addSql('ALTER TABLE product_category DROP FOREIGN KEY FK_CDFC73564584665A');
        // $this->addSql('ALTER TABLE product_group DROP FOREIGN KEY FK_CC9C3F994584665A');
        // $this->addSql('ALTER TABLE product_catalog DROP FOREIGN KEY FK_CAF529F74584665A');
        // $this->addSql('ALTER TABLE variation DROP FOREIGN KEY FK_629B33EA4584665A');
        // $this->addSql('ALTER TABLE order_entity DROP FOREIGN KEY FK_CDA754BD139DF194');
        // $this->addSql('ALTER TABLE relaypoint DROP FOREIGN KEY FK_F0ED53AD139DF194');
        // $this->addSql('ALTER TABLE good DROP FOREIGN KEY FK_6C844E923EC01A31');
        // $this->addSql('ALTER TABLE relaypoint_condition DROP FOREIGN KEY FK_9B98DFE5F8CC9BA1');
        // $this->addSql('ALTER TABLE relaypoint_user DROP FOREIGN KEY FK_343FFF77F8CC9BA1');
        // $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04AD8DE820D9');
        // $this->addSql('ALTER TABLE provision DROP FOREIGN KEY FK_BA9B42908DE820D9');
        // $this->addSql('ALTER TABLE seller_user DROP FOREIGN KEY FK_8F6A13A98DE820D9');
        // $this->addSql('ALTER TABLE supplier DROP FOREIGN KEY FK_9B2A6C7E8DE820D9');
        // $this->addSql('ALTER TABLE component DROP FOREIGN KEY FK_49FEA157498DA827');
        // $this->addSql('ALTER TABLE good DROP FOREIGN KEY FK_6C844E92498DA827');
        // $this->addSql('ALTER TABLE item DROP FOREIGN KEY FK_1F1B251E498DA827');
        // $this->addSql('ALTER TABLE container DROP FOREIGN KEY FK_C7A2EC1BDCD6110');
        // $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04ADDCD6110');
        // $this->addSql('ALTER TABLE size DROP FOREIGN KEY FK_F7C0246ADCD6110');
        // $this->addSql('ALTER TABLE supervisor_user DROP FOREIGN KEY FK_6BD776E19E9AC5F');
        // $this->addSql('ALTER TABLE provision DROP FOREIGN KEY FK_BA9B42902ADD6D8C');
        // $this->addSql('ALTER TABLE catalog_tax DROP FOREIGN KEY FK_519250B4B2A824D8');
        // $this->addSql('ALTER TABLE `condition` DROP FOREIGN KEY FK_BDD68843B2A824D8');
        // $this->addSql('ALTER TABLE container DROP FOREIGN KEY FK_C7A2EC1BB2A824D8');
        // $this->addSql('ALTER TABLE deliverer DROP FOREIGN KEY FK_97FE3348B2A824D8');
        // $this->addSql('ALTER TABLE product DROP FOREIGN KEY FK_D34A04ADB2A824D8');
        // $this->addSql('ALTER TABLE order_entity DROP FOREIGN KEY FK_CDA754BD36BD1931');
        // $this->addSql('ALTER TABLE deliverer_user DROP FOREIGN KEY FK_DBF1A092A76ED395');
        // $this->addSql('ALTER TABLE order_entity DROP FOREIGN KEY FK_CDA754BDA76ED395');
        // $this->addSql('ALTER TABLE platform_user DROP FOREIGN KEY FK_99BB165A76ED395');
        // $this->addSql('ALTER TABLE relaypoint_user DROP FOREIGN KEY FK_343FFF77A76ED395');
        // $this->addSql('ALTER TABLE seller_user DROP FOREIGN KEY FK_8F6A13A9A76ED395');
        // $this->addSql('ALTER TABLE supervisor DROP FOREIGN KEY FK_4D9192F819E9AC5F');
        // $this->addSql('ALTER TABLE supervisor_user DROP FOREIGN KEY FK_6BD776EA76ED395');
        // $this->addSql('ALTER TABLE component DROP FOREIGN KEY FK_49FEA1575182BFD8');
        // $this->addSql('ALTER TABLE good DROP FOREIGN KEY FK_6C844E925182BFD8');
        // $this->addSql('ALTER TABLE item DROP FOREIGN KEY FK_1F1B251E5182BFD8');
        // $this->addSql('ALTER TABLE size DROP FOREIGN KEY FK_F7C0246A5182BFD8');
        // $this->addSql('ALTER TABLE city DROP FOREIGN KEY FK_2D5B02349F2C3FAB');
        // $this->addSql('DROP TABLE about_us');
        // $this->addSql('DROP TABLE agent');
        // $this->addSql('DROP TABLE article');
        // $this->addSql('DROP TABLE banner');
        // $this->addSql('DROP TABLE catalog');
        // $this->addSql('DROP TABLE catalog_price');
        // $this->addSql('DROP TABLE catalog_tax');
        // $this->addSql('DROP TABLE category');
        // $this->addSql('DROP TABLE category_group');
        // $this->addSql('DROP TABLE category_catalog');
        // $this->addSql('DROP TABLE city');
        // $this->addSql('DROP TABLE city_condition');
        // $this->addSql('DROP TABLE component');
        // $this->addSql('DROP TABLE `condition`');
        // $this->addSql('DROP TABLE condition_group');
        // $this->addSql('DROP TABLE container');
        // $this->addSql('DROP TABLE countdown');
        // $this->addSql('DROP TABLE cron_job');
        // $this->addSql('DROP TABLE cron_report');
        // $this->addSql('DROP TABLE day_off');
        // $this->addSql('DROP TABLE day_off_group');
        // $this->addSql('DROP TABLE deliverer');
        // $this->addSql('DROP TABLE deliverer_user');
        // $this->addSql('DROP TABLE good');
        // $this->addSql('DROP TABLE `group`');
        // $this->addSql('DROP TABLE hero');
        // $this->addSql('DROP TABLE homepage');
        // $this->addSql('DROP TABLE item');
        // $this->addSql('DROP TABLE message');
        // $this->addSql('DROP TABLE meta');
        // $this->addSql('DROP TABLE order_entity');
        // $this->addSql('DROP TABLE package');
        // $this->addSql('DROP TABLE picture');
        // $this->addSql('DROP TABLE platform');
        // $this->addSql('DROP TABLE platform_user');
        // $this->addSql('DROP TABLE price');
        // $this->addSql('DROP TABLE price_group');
        // $this->addSql('DROP TABLE product');
        // $this->addSql('DROP TABLE product_category');
        // $this->addSql('DROP TABLE product_group');
        // $this->addSql('DROP TABLE product_catalog');
        // $this->addSql('DROP TABLE promotion');
        // $this->addSql('DROP TABLE provision');
        // $this->addSql('DROP TABLE relaypoint');
        // $this->addSql('DROP TABLE relaypoint_condition');
        // $this->addSql('DROP TABLE relaypoint_user');
        // $this->addSql('DROP TABLE reset_password');
        // $this->addSql('DROP TABLE restriction');
        // $this->addSql('DROP TABLE seller');
        // $this->addSql('DROP TABLE seller_user');
        // $this->addSql('DROP TABLE size');
        // $this->addSql('DROP TABLE stock');
        // $this->addSql('DROP TABLE supervisor');
        // $this->addSql('DROP TABLE supervisor_user');
        // $this->addSql('DROP TABLE supplier');
        // $this->addSql('DROP TABLE tax');
        // $this->addSql('DROP TABLE touring');
        // $this->addSql('DROP TABLE user');
        // $this->addSql('DROP TABLE variation');
        // $this->addSql('DROP TABLE zone');
    }
}
